### PR TITLE
GitHub Action to lint Python code

### PR DESCRIPTION
**Pull request by cclauss**
Output: https://github.com/cclauss/denver/actions

### CODE REVIEW

**Comment by cclauss** [comment]
Let's get this CI to pass before submitting to TheAlgorithms/Python.

**Comment by cclauss** [comment]
[./denver/graphics3d.py:10](https://github.com/xcodz-dot/denver/blob/master/denver/graphics3d.py#L10):43: F821 undefined name 'x'
```
def flatten(x, y, z, scale, distance) -> ("x", "y"):
                                          ^
```
`x` needs to be a datatype (int, float, list, dict, ...) not a variable name.

**Comment by cclauss** [comment]
I fixed line 10 so it passes the flake8 test.

**Comment by xcodz-dot** [comment]
well, there is an error named conflict, any idea how to fix it?
Capture

**Comment by cclauss** [comment]
Resolved.
https://docs.github.com/en/enterprise/2.13/user/articles/resolving-a-merge-conflict-on-github

**Comment by xcodz-dot** [comment]
please review my new pull request, it is completely compiled with all you documentation and requirements, travis build also passed

**Pull request merged**
